

import { Category, Dish, Action, Language } from './types';

export const THEME = {
  primary: "bg-rose-500",
  primaryText: "text-rose-600",
  primaryBorder: "border-rose-200",
  primaryHover: "hover:bg-rose-600",
  lightBg: "bg-rose-50",
  gradient: "bg-gradient-to-r from-rose-500 to-pink-600",
  chatUserBg: "bg-gradient-to-br from-rose-500 to-pink-600 text-white shadow-md shadow-rose-200",
  chatBotBg: "bg-white text-gray-800 shadow-sm border border-gray-100",
};

export const TRANSLATIONS = {
  ru: {
    greeting: '👋 Привет! Я ИИ-ассистент Foodi AI. Чем могу помочь?',
    cartTitle: 'Корзина',
    paymentTitle: 'Оплата',
    successTitle: 'Готово',
    emptyCart: 'В корзине пусто',
    emptyCartDesc: 'Добавьте вкусные блюда из меню',
    goToMenu: 'Перейти к меню',
    addToOrder: 'Добавить к заказу?',
    paymentMethod: 'Способ оплаты',
    card: 'Банковская карта',
    applePay: 'Apple Pay',
    cash: 'Наличными',
    cashDesc: 'При получении',
    fastPay: 'Быстрая оплата',
    orderTotal: 'Сумма заказа',
    service: 'Обслуживание',
    total: 'Итого',
    pay: 'Оплатить',
    processing: 'Обработка...',
    back: 'Назад',
    orderPaid: 'Заказ оплачен!',
    successDesc: 'Спасибо за заказ. Мы уже начали его готовить. Приятного аппетита!',
    orderNum: 'Номер заказа',
    excellent: 'Отлично',
    dineIn: 'В зале',
    takeaway: 'С собой',
    delivery: 'Доставка',
    yourTable: 'Ваш столик',
    tablePlaceholder: '№ столика',
    timeReady: 'Время готовности',
    asap: '🚀 Как можно скорее',
    addressPlaceholder: 'Улица, дом',
    mapBtn: 'Выбрать на карте',
    commentPlaceholder: 'Комментарий к заказу (подъезд, этаж)...',
    fillAddress: 'Укажите адрес/время',
    fillTable: 'Укажите столик',
    toPay: 'К оплате',
    returnToShop: 'Вернуться к покупкам',
    mapSelection: 'Перемещайте карту',
    selectedAddress: 'Выбранный адрес',
    confirmAddress: 'Подтвердить адрес',
    showMenu: 'Посмотреть меню',
    recommendations: 'Рекомендации',
    askQuestion: 'Задать вопрос',
    callWaiter: '🔔 Позвать официанта',
    startOver: '🔄 Начать заново',
    checkStatus: 'Статус заказа',
    callWaiterChat: '🔔 Официант вызван к столику',
    statusAccepted: 'Принят',
    statusCooking: 'Готовится',
    statusReady: 'Готов',
    statusWay: 'В пути',
    statusCompleted: 'Завершен',
    orderContents: 'Состав заказа',
    moreItems: 'и еще',
    today: 'Сегодня',
    online: 'Online',
    inputPlaceholder: 'Напишите сообщение...',
    profileAddress: 'Адрес',
    address: 'Адрес',
    profileTime: 'Время работы',
    profilePhone: 'Телефон',
    areYouIn: 'Вы в заведении?',
    callWaiterBtn: 'Вызвать официанта',
    callWaiterModalTitle: 'Вызов официанта',
    enterTableNum: 'Введите номер столика:',
    cancel: 'Отмена',
    call: 'Вызвать',
    langChanged: 'Язык изменен на Русский 🇷🇺',
    resetChat: '🔄 Чат сброшен. Привет! Я ИИ-ассистент Foodi AI. Чем могу помочь?',
    chooseCategory: 'Выберите категорию меню:',
    hereIs: 'Вот что у нас есть в категории',
    wantMore: 'Хотите посмотреть что-то еще?',
    show: 'Показать',
    advice: 'Посоветуй что-нибудь',
    hits: 'С удовольствием! Вот наши абсолютные хиты 🌟😋',
    writeQuestion: 'Напишите ваш вопрос в поле внизу, и я постараюсь ответить!',
    learning: 'Я пока учусь, но скоро смогу отвечать на любые вопросы! А пока посмотрите меню.',
    orderAccepted: '✅ Ваш заказ принят! Мы уже начали готовить.',
    trackStatus: 'Вы можете отслеживать статус заказа прямо здесь.',
    courierWay: '🚴 Курьер забрал ваш заказ! Уже в пути.',
    orderReady: '✅ Заказ готов! Приятного аппетита.',
    kitchenCooking: '👩‍🍳 Кухня приняла заказ! Готовим ваши блюда.',
    statusInfo: 'Вот статус вашего текущего заказа:',
    noOrders: 'У вас пока нет активных заказов. Хотите что-нибудь выбрать?',
    addToCart: 'В корзину',
    min: 'мин',
    pcs: 'шт',
  },
  en: {
    greeting: '👋 Hi! I am Foodi AI assistant. How can I help you?',
    cartTitle: 'Cart',
    paymentTitle: 'Payment',
    successTitle: 'Done',
    emptyCart: 'Cart is empty',
    emptyCartDesc: 'Add some delicious food from the menu',
    goToMenu: 'Go to Menu',
    addToOrder: 'Add to order?',
    paymentMethod: 'Payment Method',
    card: 'Credit Card',
    applePay: 'Apple Pay',
    cash: 'Cash',
    cashDesc: 'Upon receipt',
    fastPay: 'Fast payment',
    orderTotal: 'Order Total',
    service: 'Service',
    total: 'Total',
    pay: 'Pay',
    processing: 'Processing...',
    back: 'Back',
    orderPaid: 'Order Paid!',
    successDesc: 'Thank you for your order. We have already started preparing it. Enjoy!',
    orderNum: 'Order #',
    excellent: 'Excellent',
    dineIn: 'Dine-in',
    takeaway: 'Takeaway',
    delivery: 'Delivery',
    yourTable: 'Your table',
    tablePlaceholder: 'Table No.',
    timeReady: 'Ready time',
    asap: '🚀 As soon as possible',
    addressPlaceholder: 'Street, house',
    mapBtn: 'Select on map',
    commentPlaceholder: 'Order comment (entrance, floor)...',
    fillAddress: 'Enter address/time',
    fillTable: 'Enter table number',
    toPay: 'To Pay',
    returnToShop: 'Return to shopping',
    mapSelection: 'Move the map',
    selectedAddress: 'Selected address',
    confirmAddress: 'Confirm address',
    showMenu: 'View Menu',
    recommendations: 'Recommendations',
    askQuestion: 'Ask a question',
    callWaiter: '🔔 Call Waiter',
    startOver: '🔄 Start Over',
    checkStatus: 'Order Status',
    callWaiterChat: '🔔 Waiter called to table',
    statusAccepted: 'Accepted',
    statusCooking: 'Cooking',
    statusReady: 'Ready',
    statusWay: 'On the way',
    statusCompleted: 'Completed',
    orderContents: 'Order contents',
    moreItems: 'and more',
    today: 'Today',
    online: 'Online',
    inputPlaceholder: 'Type a message...',
    profileAddress: 'Address',
    address: 'Address',
    profileTime: 'Working Hours',
    profilePhone: 'Phone',
    areYouIn: 'Are you in the restaurant?',
    callWaiterBtn: 'Call Waiter',
    callWaiterModalTitle: 'Call Waiter',
    enterTableNum: 'Enter table number:',
    cancel: 'Cancel',
    call: 'Call',
    langChanged: 'Language changed to English 🇺🇸',
    resetChat: '🔄 Chat reset. Hi! I am Foodi AI assistant. How can I help?',
    chooseCategory: 'Choose a menu category:',
    hereIs: 'Here is what we have in',
    wantMore: 'Want to see something else?',
    show: 'Show',
    advice: 'Recommend something',
    hits: 'With pleasure! Here are our absolute hits 🌟😋',
    writeQuestion: 'Write your question below and I will try to answer!',
    learning: 'I am still learning, but soon I will answer any questions! For now, check the menu.',
    orderAccepted: '✅ Your order is accepted! We started cooking.',
    trackStatus: 'You can track the order status right here.',
    courierWay: '🚴 Courier picked up your order! On the way.',
    orderReady: '✅ Order is ready! Enjoy your meal.',
    kitchenCooking: '👩‍🍳 Kitchen accepted the order! Cooking now.',
    statusInfo: 'Here is your current order status:',
    noOrders: 'You have no active orders. Want to choose something?',
    addToCart: 'Add',
    min: 'min',
    pcs: 'pcs',
  },
  ar: {
    greeting: '👋 مرحبًا! أنا مساعد Foodi AI. كيف يمكنني مساعدتك؟',
    cartTitle: 'عربة التسوق',
    paymentTitle: 'الدفع',
    successTitle: 'تم',
    emptyCart: 'العربة فارغة',
    emptyCartDesc: 'أضف بعض الطعام اللذيذ من القائمة',
    goToMenu: 'الذهاب للقائمة',
    addToOrder: 'إضافة للطلب؟',
    paymentMethod: 'طريقة الدفع',
    card: 'بطاقة ائتمان',
    applePay: 'Apple Pay',
    cash: 'نقدي',
    cashDesc: 'عند الاستلام',
    fastPay: 'دفع سريع',
    orderTotal: 'مجموع الطلب',
    service: 'الخدمة',
    total: 'المجموع',
    pay: 'دفع',
    processing: 'جاري المعالجة...',
    back: 'رجوع',
    orderPaid: 'تم دفع الطلب!',
    successDesc: 'شكرا لطلبك. لقد بدأنا بالفعل في تحضيره. بالعافية!',
    orderNum: 'رقم الطلب',
    excellent: 'ممتاز',
    dineIn: 'في المطعم',
    takeaway: 'سفري',
    delivery: 'توصيل',
    yourTable: 'طاولتك',
    tablePlaceholder: 'رقم الطاولة',
    timeReady: 'وقت الجاهزية',
    asap: '🚀 في أقرب وقت ممكن',
    addressPlaceholder: 'الشارع، المنزل',
    mapBtn: 'تحديد على الخريطة',
    commentPlaceholder: 'تعليق الطلب (المدخل، الطابق)...',
    fillAddress: 'أدخل العنوان/الوقت',
    fillTable: 'أدخل رقم الطاولة',
    toPay: 'للدفع',
    returnToShop: 'العودة للتسوق',
    mapSelection: 'حرك الخريطة',
    selectedAddress: 'العنوان المحدد',
    confirmAddress: 'تأكيد العنوان',
    showMenu: 'عرض القائمة',
    recommendations: 'توصيات',
    askQuestion: 'طرح سؤال',
    callWaiter: '🔔 استدعاء النادل',
    startOver: '🔄 البدء من جديد',
    checkStatus: 'حالة الطلب',
    callWaiterChat: '🔔 تم استدعاء النادل للطاولة',
    statusAccepted: 'مقبول',
    statusCooking: 'يتم التحضير',
    statusReady: 'جاهز',
    statusWay: 'في الطريق',
    statusCompleted: 'مكتمل',
    orderContents: 'محتويات الطلب',
    moreItems: 'و المزيد',
    today: 'اليوم',
    online: 'متصل',
    inputPlaceholder: 'اكتب رسالة...',
    profileAddress: 'العنوان',
    address: 'العنوان',
    profileTime: 'ساعات العمل',
    profilePhone: 'الهاتف',
    areYouIn: 'هل أنت في المطعم؟',
    callWaiterBtn: 'استدعاء النادل',
    callWaiterModalTitle: 'استدعاء النادل',
    enterTableNum: 'أدخل رقم الطاولة:',
    cancel: 'إلغاء',
    call: 'اتصال',
    langChanged: 'تم تغيير اللغة إلى العربية 🇸🇦',
    resetChat: '🔄 تم إعادة تعيين الدردشة. مرحبًا! كيف يمكنني المساعدة؟',
    chooseCategory: 'اختر فئة القائمة:',
    hereIs: 'إليك ما لدينا في',
    wantMore: 'هل تريد رؤية شيء آخر؟',
    show: 'عرض',
    advice: 'انصحني بشيء',
    hits: 'بكل سرور! إليك أفضل أطباقنا 🌟😋',
    writeQuestion: 'اكتب سؤالك في الأسفل وسأحاول الإجابة!',
    learning: 'ما زلت أتعلم، ولكن قريبًا سأجيب على أي أسئلة! حاليًا، تفقد القائمة.',
    orderAccepted: '✅ تم قبول طلبك! بدأنا التحضير.',
    trackStatus: 'يمكنك تتبع حالة الطلب هنا.',
    courierWay: '🚴 المندوب استلم طلبك! في الطريق.',
    orderReady: '✅ الطلب جاهز! بالعافية.',
    kitchenCooking: '👩‍🍳 المطبخ قبل الطلب! يتم التحضير.',
    statusInfo: 'إليك حالة طلبك الحالي:',
    noOrders: 'ليس لديك طلبات نشطة. هل تريد اختيار شيء ما؟',
    addToCart: 'أضف',
    min: 'د',
    pcs: 'قطعة',
  }
};

const RAW_CATEGORIES = [
  { id: 'pizza', emoji: '🍕', names: { ru: 'Пицца', en: 'Pizza', ar: 'بيتزا' } },
  { id: 'sushi', emoji: '🍣', names: { ru: 'Суши', en: 'Sushi', ar: 'سوشي' } },
  { id: 'desserts', emoji: '🧁', names: { ru: 'Десерты', en: 'Desserts', ar: 'حلويات' } },
  { id: 'drinks', emoji: '🥤', names: { ru: 'Напитки', en: 'Drinks', ar: 'مشروبات' } },
];

const RAW_MENU_ITEMS: Record<string, any[]> = {
  'pizza': [
    { id: 'p1', price: 2500, time: '15', img: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=300&q=80', names: { ru: 'Маргарита', en: 'Margherita', ar: 'مارغريتا' }, descs: { ru: 'Томатный соус, моцарелла, базилик', en: 'Tomato sauce, mozzarella, basil', ar: 'صلصة طماطم، موزاريلا، ريحان' } },
    { id: 'p2', price: 2800, time: '18', img: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=300&q=80', names: { ru: 'Пепперони', en: 'Pepperoni', ar: 'بيبروني' }, descs: { ru: 'Пикантная пепперони, моцарелла', en: 'Spicy pepperoni, mozzarella', ar: 'بيبروني حار، موزاريلا' } },
    { id: 'p3', price: 3000, time: '20', img: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=300&q=80', names: { ru: 'Четыре сыра', en: 'Four Cheese', ar: 'أربعة أجبان' }, descs: { ru: 'Моцарелла, пармезан, горгонзола, эмменталь', en: 'Mozzarella, parmesan, gorgonzola, emmental', ar: 'موزاريلا، بارميزان، جورجونزولا، إيمنتال' } },
    { id: 'p4', price: 2700, time: '17', img: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=300&q=80', names: { ru: 'Гавайская', en: 'Hawaiian', ar: 'هاواي' }, descs: { ru: 'Курица, ананасы, моцарелла', en: 'Chicken, pineapple, mozzarella', ar: 'دجاج، أناناس، موزاريلا' } },
  ],
  'sushi': [
    { id: 's1', price: 2200, time: '12', img: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=300&q=80', names: { ru: 'Филадельфия', en: 'Philadelphia', ar: 'فيلادلفيا' }, descs: { ru: 'Лосось, сливочный сыр, огурец', en: 'Salmon, cream cheese, cucumber', ar: 'سلمون، جبنة كريمية، خيار' } },
    { id: 's2', price: 1900, time: '12', img: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=300&q=80', names: { ru: 'Калифорния', en: 'California', ar: 'كاليفورنيا' }, descs: { ru: 'Краб, авокадо, огурец, тобико', en: 'Crab, avocado, cucumber, tobiko', ar: 'سلطعون، أفوكادو، خيار، توبيكو' } },
    { id: 's3', price: 2400, time: '14', img: 'https://images.unsplash.com/photo-1617196019294-dc359e3e7518?auto=format&fit=crop&w=300&q=80', names: { ru: 'Канада', en: 'Canada', ar: 'كندا' }, descs: { ru: 'Угорь, сливочный сыр, авокадо, унаги соус', en: 'Eel, cream cheese, avocado, unagi sauce', ar: 'ثعبان البحر، جبنة كريمية، أفوكادو، صلصة أوناغي' } },
  ],
  'desserts': [
    { id: 'd1', price: 1000, time: '4', img: 'https://images.unsplash.com/photo-1524351199678-941a58a3df50?auto=format&fit=crop&w=300&q=80', names: { ru: 'Чизкейк', en: 'Cheesecake', ar: 'تشيز كيك' }, descs: { ru: 'Классический чизкейк Нью-Йорк', en: 'Classic New York Cheesecake', ar: 'تشيز كيك نيويورك الكلاسيكي' } },
    { id: 'd2', price: 950, time: '3', img: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?auto=format&fit=crop&w=300&q=80', names: { ru: 'Тирамису', en: 'Tiramisu', ar: 'تيراميسو' }, descs: { ru: 'Кофейный десерт', en: 'Coffee dessert', ar: 'حلوى القهوة' } },
    { id: 'd3', price: 900, time: '3', img: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=300&q=80', names: { ru: 'Брауни', en: 'Brownie', ar: 'براوني' }, descs: { ru: 'Шоколадный пирог с орехами', en: 'Chocolate cake with nuts', ar: 'كعكة الشوكولاتة بالمكسرات' } },
  ],
  'drinks': [
    { id: 'n1', price: 800, time: '2', img: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=300&q=80', names: { ru: 'Лимонад', en: 'Lemonade', ar: 'ليمونادة' }, descs: { ru: 'Домашний цитрусовый лимонад', en: 'Homemade citrus lemonade', ar: 'ليمونادة حمضيات محلية الصنع' } },
    { id: 'n2', price: 300, time: '1', img: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=300&q=80', names: { ru: 'Кола', en: 'Cola', ar: 'كولا' }, descs: { ru: '0.5л', en: '0.5L', ar: '0.5 لتر' } },
    { id: 'n3', price: 600, time: '2', img: 'https://images.unsplash.com/photo-1499638673689-79a0b5115d87?auto=format&fit=crop&w=300&q=80', names: { ru: 'Чай Ice', en: 'Ice Tea', ar: 'شاي مثلج' }, descs: { ru: 'Холодный чай с персиком', en: 'Cold tea with peach', ar: 'شاي بارد بالخوخ' } },
  ]
};

export const getCategories = (lang: Language): Category[] => {
  return RAW_CATEGORIES.map(cat => ({
    id: cat.id,
    name: cat.names[lang] || cat.names.ru,
    emoji: cat.emoji
  }));
};

export const getMenuData = (lang: Language): Record<string, Dish[]> => {
  const t = TRANSLATIONS[lang];
  const menu: Record<string, Dish[]> = {};
  
  // Need to map Category Names (localized) to their items
  const categories = getCategories(lang);
  
  categories.forEach(cat => {
     const rawItems = RAW_MENU_ITEMS[cat.id] || [];
     menu[cat.name] = rawItems.map(item => ({
        id: item.id,
        name: item.names[lang] || item.names.ru,
        price: item.price,
        time: `${item.time} ${t.min}`,
        img: item.img,
        desc: item.descs[lang] || item.descs.ru
     }));
  });
  
  return menu;
};

// Also export MENU_DATA for compatibility if needed, but App.tsx should use getMenuData
// For initial render/types we can keep empty object or default
export const MENU_DATA = getMenuData('ru');
export const CATEGORIES = getCategories('ru');

export const getInitialActions = (lang: Language): Action[] => {
  const t = TRANSLATIONS[lang];
  return [
    { label: t.showMenu, action: 'show_categories' },
    { label: t.recommendations, action: 'show_recommendations' },
    { label: t.askQuestion, action: 'ask_question' },
  ];
};

export const INITIAL_ACTIONS = getInitialActions('ru');
